### ISSUE TITLE
[oneDPL] [Iterators] Add a method to extract underlying iterators

### ISSUE THREAD

**Issue by andreyfe1** [oneapi-src/oneAPI-spec#397] opened 2021-12-24 07:34 UTC
It would be great if `zip_iterator` has a method that extracts tuple of underlying iterators. Probably it would be useful for some other iterators as well (e.g. `transform_iterator`).
I see that oneDPL implementation already contains it: https://github.com/oneapi-src/oneDPL/blob/main/include/oneapi/dpl/pstl/iterator_impl.h#L364

**Comment by MikeDvorskiy** [comment] 2022-01-19 09:23
Ok. So, the issue should be closed.

**Comment by capatober** [comment] 2022-01-19 09:34
Issue is still relevant since oneDPL spec doesn't specify that method. The issue is for the Spec, not for the implementation

**Comment by akukanov** [comment] 2022-11-08 16:09
Addressed in v1.2 specification

**Closed by akukanov** 2022-11-08 16:09 UTC
Labels: enhancement, DPL
